# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_EXYNOS9610) += \
	exynos9611-a51_eur_open_00.dtbo \
	exynos9611-a51_eur_open_01.dtbo \
	exynos9611-a51_eur_open_03.dtbo \
	exynos9611-a51_eur_open_07.dtbo

always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
